// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-layouts/ActionDashboard.tsx": () => import("../components/mockups/home-layouts/ActionDashboard.tsx"),
  "./components/mockups/home-layouts/Current.tsx": () => import("../components/mockups/home-layouts/Current.tsx"),
  "./components/mockups/home-layouts/EditorialMagazine.tsx": () => import("../components/mockups/home-layouts/EditorialMagazine.tsx"),
  "./components/mockups/home-layouts/NarrativeScroll.tsx": () => import("../components/mockups/home-layouts/NarrativeScroll.tsx")
};
